#!/usr/bin/env python3
"""git log BR 코드 → 모듈별 BR-COMMITS.md + 집계 BR-COVERAGE.md 생성기.

입력:
  - `git log --all --pretty=format:"%h|%ai|%s"` 전체 커밋
  - docs/product/scope/BR-MODULE-MAP.toml (prefix → 모듈 매핑)
  - docs/product/scope/modules/<module>/L2-spec.md (있으면 BR 매핑 상태 판정용)

출력:
  - docs/product/scope/modules/<module>/BR-COMMITS.md (prefix에 매핑된 모듈만)
  - docs/product/scope/BR-COVERAGE.md (전체 집계)

사용:
  python3 scripts/docs/sync_br_codes.py          # dry-run (diff 출력, 종료 1 if drift)
  python3 scripts/docs/sync_br_codes.py --write  # 실제 파일 기록
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tomllib
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MAP_PATH = ROOT / "docs" / "product" / "scope" / "BR-MODULE-MAP.toml"
MODULES_DIR = ROOT / "docs" / "product" / "scope" / "modules"
COVERAGE_PATH = ROOT / "docs" / "product" / "scope" / "BR-COVERAGE.md"

BR_PATTERN = re.compile(r"BR-([A-Z]+)-([A-Z0-9][A-Z0-9,\-~/]*)")


def _git_log() -> list[tuple[str, str, str]]:
    git_cmd = shutil.which("git") or "git"
    out = subprocess.run(
        [git_cmd, "log", "--all", "--pretty=format:%h|%ai|%s"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    records: list[tuple[str, str, str]] = []
    for line in out.splitlines():
        parts = line.split("|", 2)
        if len(parts) == 3:
            h, date, subject = parts
            records.append((h, date[:10], subject))
    return records


def _parse_br_occurrences(records):
    """(prefix, raw_br_string, wave) 단위로 집계. prefix → list[dict]."""
    per_prefix: dict[str, list[dict]] = defaultdict(list)
    for h, date, subject in records:
        wave_m = re.search(r"\((Wave\s+[\w\-\.]+|M0\s+PR-\d+\.\d+)\)", subject)
        wave = wave_m.group(1) if wave_m else ""
        for m in BR_PATTERN.finditer(subject):
            prefix = m.group(1)
            raw = m.group(0)
            per_prefix[prefix].append(
                {"br": raw, "commit": h, "date": date, "wave": wave, "subject": subject}
            )
    return per_prefix


def _render_module_page(module: str, prefix: str, entries: list[dict]) -> str:
    lines = [
        "<!-- AUTO-GENERATED by scripts/docs/sync_br_codes.py — DO NOT EDIT -->",
        f"<!-- MODULE: {module}  PREFIX: BR-{prefix}  COUNT: {len(entries)} -->",
        "",
        f"# BR ↔ 커밋 매핑: `{module}`",
        "",
        f"prefix **BR-{prefix}** 가 포함된 커밋 전수. 수정은 `versions.toml`/`BR-MODULE-MAP.toml` 을 거쳐 `sync_br_codes.py --write` 로 수행하세요.",
        "",
        "| BR 코드 | commit | 날짜 | Wave | 제목 |",
        "|---|---|---|---|---|",
    ]
    # 최근순 정렬
    for e in sorted(entries, key=lambda x: x["date"], reverse=True):
        subject_cell = e["subject"].replace("|", "\\|")
        lines.append(
            f"| `{e['br']}` | `{e['commit']}` | {e['date']} | {e['wave']} | {subject_cell} |"
        )
    lines.append("")
    return "\n".join(lines)


def _l2_has_br(module: str, prefix: str) -> bool:
    l2 = MODULES_DIR / module / "L2-spec.md"
    if not l2.exists():
        return False
    return f"BR-{prefix}" in l2.read_text(encoding="utf-8", errors="ignore")


def _render_coverage(mapping: dict, per_prefix: dict, modules_all: list[str]) -> str:
    total_modules = len(modules_all)
    prefix_mapped_modules: set[str] = set()
    for mods in mapping.values():
        prefix_mapped_modules.update(mods)
    unmapped = sorted(m for m in modules_all if m not in prefix_mapped_modules)

    lines = [
        "<!-- AUTO-GENERATED by scripts/docs/sync_br_codes.py — DO NOT EDIT -->",
        "",
        "# BR 커버리지 집계",
        "",
        f"- 총 모듈: **{total_modules}**",
        f"- BR prefix 매핑된 모듈: **{len(prefix_mapped_modules)}**",
        f"- 미매핑 모듈: **{len(unmapped)}**",
        "",
        "## prefix 별 커밋 집계",
        "",
        "| prefix | 커밋 수 | 매핑 모듈 | L2-spec 매핑 상태 |",
        "|---|---|---|---|",
    ]
    for prefix in sorted(mapping.keys()):
        mods = mapping[prefix]
        count = len(per_prefix.get(prefix, []))
        l2_status = []
        for m in mods:
            mark = "✓" if _l2_has_br(m, prefix) else "·"
            l2_status.append(f"{m}{mark}")
        lines.append(f"| BR-{prefix} | {count} | {', '.join(mods)} | {', '.join(l2_status)} |")

    lines += [
        "",
        "*범례*: ✓ = L2-spec.md 에 해당 prefix 가 이미 언급됨 / · = 미언급",
        "",
        "## 매핑 정의 외 prefix (yaml 갱신 필요)",
        "",
    ]
    extra = sorted(set(per_prefix.keys()) - set(mapping.keys()))
    if extra:
        for p in extra:
            lines.append(
                f"- BR-{p} ({len(per_prefix[p])} commit) — `BR-MODULE-MAP.toml` 에 추가 필요"
            )
    else:
        lines.append("*없음 (모든 prefix 가 매핑 정의되어 있음)*")

    lines += [
        "",
        "## 매핑 정의는 있으나 BR 커밋 0건",
        "",
    ]
    zero = sorted(p for p in mapping if p not in per_prefix)
    if zero:
        for p in zero:
            lines.append(f"- BR-{p} (0 commit) — 아직 실구현 커밋 없음")
    else:
        lines.append("*없음 (모든 정의된 prefix 에 커밋이 있음)*")

    lines += ["", "## BR 매핑이 없는 모듈", ""]
    if unmapped:
        for m in unmapped:
            lines.append(f"- {m}")
    else:
        lines.append("*없음 (모든 모듈이 매핑되어 있음)*")
    lines.append("")
    return "\n".join(lines)


def _write_or_diff(path: Path, new_text: str, *, write: bool) -> bool:
    """기록되어야 하는 drift 가 있으면 True."""
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if current == new_text:
            return False
    if write:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new_text, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()

    if not MAP_PATH.exists():
        print(f"ERROR: {MAP_PATH} 없음.", file=sys.stderr)
        return 2

    spec = tomllib.loads(MAP_PATH.read_text(encoding="utf-8"))
    mapping: dict[str, list[str]] = spec["mappings"]

    modules_all = sorted(p.name for p in MODULES_DIR.iterdir() if p.is_dir())

    records = _git_log()
    per_prefix = _parse_br_occurrences(records)

    drift = 0
    for prefix, mods in mapping.items():
        entries = per_prefix.get(prefix, [])
        if not entries:
            continue
        for module in mods:
            out = MODULES_DIR / module / "BR-COMMITS.md"
            body = _render_module_page(module, prefix, entries)
            if _write_or_diff(out, body, write=args.write):
                drift += 1
                rel = out.relative_to(ROOT)
                marker = "→ 갱신" if args.write else "drift"
                print(f"△ {rel}: {marker}")

    coverage_body = _render_coverage(mapping, per_prefix, modules_all)
    if _write_or_diff(COVERAGE_PATH, coverage_body, write=args.write):
        drift += 1
        rel = COVERAGE_PATH.relative_to(ROOT)
        marker = "→ 갱신" if args.write else "drift"
        print(f"△ {rel}: {marker}")

    mapped = sum(1 for k in mapping if k in per_prefix)
    print()
    print(f"prefix {len(mapping)}개 중 커밋 보유 {mapped}개 / 전체 drift {drift}개")

    if drift > 0 and not args.write:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
