"""BE 모델 스캐폴드 생성기."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from jinja2 import Environment, FileSystemLoader

from scripts.codegen.catalog import SERVICES_DIR
from scripts.codegen.naming import pascal_to_snake

if TYPE_CHECKING:
    from scripts.codegen.catalog import CatalogEntry

_GENERATED_MARKER = "# GENERATED BY CODEGEN"
_TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates"


def _get_jinja_env() -> Environment:
    """Jinja2 환경을 반환한다."""
    return Environment(
        loader=FileSystemLoader(str(_TEMPLATES_DIR)),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
        autoescape=False,  # noqa: S701 — 코드 생성용 (HTML 아님)
    )


def _parse_workflow_states(workflow_str: str) -> list[str]:
    """워크플로우 문자열에서 상태 목록을 추출한다.

    예시: "draft→submitted→cancelled" → ["DRAFT", "SUBMITTED", "CANCELLED"]
    """
    if not workflow_str or workflow_str.startswith(("없음", "자동")):
        return []

    states: list[str] = []
    for part in workflow_str.replace("→", ";").replace(";", ";").split(";"):
        state = part.strip().upper()
        if state:
            states.append(state)
    return list(dict.fromkeys(states))  # 중복 제거 (순서 유지)


def generate_be_model(
    entry: CatalogEntry,
    services_dir: Path | None = None,
    *,
    dry_run: bool = False,
) -> Path | None:
    """BE 모델 스캐폴드를 생성한다.

    반환: 생성된 파일 경로 (dry_run이면 생성 예정 경로만 반환).
    이미 존재하고 GENERATED_MARKER가 없으면 건너뛴다.
    """
    svc_dir = services_dir or SERVICES_DIR
    target_dir = svc_dir / entry.service / "app" / "models"
    filename = pascal_to_snake(entry.doctype_or_entity) + ".py"
    target_path = target_dir / filename

    # 이미 존재하는 파일은 수동 편집된 것이면 건너뛰기
    if target_path.exists():
        content = target_path.read_text(encoding="utf-8")
        if _GENERATED_MARKER not in content:
            print(f"  [건너뜀] {target_path.relative_to(svc_dir)} (수동 편집 감지)")
            return None

    if dry_run:
        return target_path

    # 디렉토리가 없으면 생성
    target_dir.mkdir(parents=True, exist_ok=True)

    env = _get_jinja_env()
    template = env.get_template("be_model.py.j2")

    states = _parse_workflow_states(entry.workflows)
    rendered = template.render(
        entity_name=entry.doctype_or_entity,
        module_name=entry.module,
        feature_name=entry.feature,
        snake_name=pascal_to_snake(entry.doctype_or_entity),
        states=states,
        notes=entry.notes,
        generated_marker=_GENERATED_MARKER,
    )

    target_path.write_text(rendered, encoding="utf-8")
    print(f"  [생성] {target_path.relative_to(svc_dir)}")
    return target_path
