"""FE EntityConfig 스캐폴드 생성기."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from jinja2 import Environment, FileSystemLoader

from scripts.codegen.catalog import FE_MODULES_DIR
from scripts.codegen.naming import pascal_to_snake

if TYPE_CHECKING:
    from scripts.codegen.catalog import CatalogEntry

_GENERATED_MARKER = "// GENERATED BY CODEGEN"
_TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates"


def _get_jinja_env() -> Environment:
    """Jinja2 환경을 반환한다."""
    return Environment(
        loader=FileSystemLoader(str(_TEMPLATES_DIR)),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
        autoescape=False,  # noqa: S701 — 코드 생성용 (HTML 아님)
    )


def _entity_to_fe_filename(entity_name: str) -> str:
    """엔티티명을 FE 모듈 파일명(kebab-case 복수형)으로 변환한다."""
    snake = pascal_to_snake(entity_name)
    kebab = snake.replace("_", "-")
    # 간단한 복수형 처리
    if kebab.endswith("y") and not kebab.endswith("ey"):
        kebab = kebab[:-1] + "ies"
    elif kebab.endswith(("s", "x", "sh")):
        kebab += "es"
    else:
        kebab += "s"
    return kebab


def _parse_permissions(perm_str: str) -> list[str]:
    """권한 문자열을 파싱한다."""
    if not perm_str:
        return []
    return [p.strip() for p in perm_str.split(";") if p.strip()]


def generate_fe_module(
    entry: CatalogEntry,
    fe_dir: Path | None = None,
    *,
    dry_run: bool = False,
) -> Path | None:
    """FE EntityConfig 스캐폴드를 생성한다.

    반환: 생성된 파일 경로 (dry_run이면 생성 예정 경로만 반환).
    이미 존재하고 GENERATED_MARKER가 없으면 건너뛴다.
    """
    modules_dir = fe_dir or FE_MODULES_DIR
    filename = _entity_to_fe_filename(entry.doctype_or_entity) + ".ts"
    target_path = modules_dir / filename

    # 이미 존재하는 파일은 수동 편집된 것이면 건너뛰기
    if target_path.exists():
        content = target_path.read_text(encoding="utf-8")
        if _GENERATED_MARKER not in content:
            print(f"  [건너뜀] {filename} (수동 편집 감지)")
            return None

    if dry_run:
        return target_path

    modules_dir.mkdir(parents=True, exist_ok=True)

    env = _get_jinja_env()
    template = env.get_template("fe_module.ts.j2")

    permissions = _parse_permissions(entry.permissions)
    api_base = ""
    if entry.api_endpoints:
        # 첫 번째 엔드포인트에서 base URL 추출
        first_ep = entry.api_endpoints.split(";")[0].strip()
        # "POST /api/xxx" 또는 "GET /api/xxx/{id}" 에서 경로 추출
        parts = first_ep.split()
        if len(parts) >= 2:
            api_base = parts[1].split("{")[0].rstrip("/")

    rendered = template.render(
        entity_name=entry.doctype_or_entity,
        feature_name=entry.feature,
        module_name=entry.module,
        kebab_name=_entity_to_fe_filename(entry.doctype_or_entity),
        api_base=api_base,
        permissions=permissions,
        roles=entry.roles,
        page_url=entry.page_urls,
        generated_marker=_GENERATED_MARKER,
    )

    target_path.write_text(rendered, encoding="utf-8")
    print(f"  [생성] {filename}")
    return target_path
